### ISSUE TITLE
It give me this error how can i fix?

### ISSUE THREAD

**Issue by SimontechGaming** [Seconds123/no1-playerped#3]
![immagine](https://user-images.githubusercontent.com/124149796/216020936-61fc0675-0007-43af-98c3-b5f4a57b8ef2.png)

**Comment by Seconds123** [comment]
A whole rewrite has been done, test it and open an issue if the issue still persists.

**Comment by Seconds123** [comment]
A whole rewrite has been done, test it and open an issue if the issue still persists.
